### ISSUE TITLE
AttributeError: _ARRAY_API not found in Numpy 2.0.0

### ISSUE THREAD

**Issue by WhiteSymmetry** [conda-forge/jaxlib-feedstock#259]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Description
File "/home//lib/python3.11/site-packages/jax/_src/lib/init.py", line 87, in
import jaxlib.xla_client as xla_client
File "/home//lib/python3.11/site-packages/jaxlib/xla_client.py", line 32, in
from . import xla_extension as _xla
AttributeError Traceback (most recent call last)
AttributeError: _ARRAY_API not found

Numpy: 1.x
It doesn’t give an error in numpy 1.x.

System info (python version, jaxlib version, accelerator, etc.)
jax: 0.4.27
jaxlib: 0.4.23.dev20240125 & 0.4.23.dev20240522
numpy: 2.0.0
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:53:30) [GCC 12.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='mk', release='6.9.3-060903-generic', version='#202405300957 SMP PREEMPT_DYNAMIC Thu May 30 11:39:13 UTC 2024', machine='x86_64')

### Installed packages

```shell
conda list
# packages in environment at /home/*/miniconda3/envs/x11:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   haa98f57_10  
_x86_64-microarch-level   1                         2_k10    conda-forge
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
anytree                   2.12.1                   pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
at-spi2-atk               2.38.0               h0630a04_3    conda-forge
at-spi2-core              2.40.3               h0630a04_0    conda-forge
atk-1.0                   2.38.0               h04ea711_2    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.2.0                   pypi_0    pypi
babel                     2.15.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
binutils_impl_linux-64    2.40                 ha1999f0_2    conda-forge
bleach                    6.1.0                    pypi_0    pypi
bootstrap                 4.4.1                         0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.6.2             hbcca054_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
cairomm-1.16              1.16.2               h7e731d7_1    conda-forge
certifi                   2024.6.2        py311h06a4308_0  
cffi                      1.16.0          py311hb3a22ac_0    conda-forge
charset-normalizer        3.3.2                    pypi_0    pypi
cirq-core                 1.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
contourpy                 1.2.1           py311h9547e67_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.10          py311h5eee18b_0  
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.8.1           py311hb755f60_0    conda-forge
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
duet                      0.2.9                    pypi_0    pypi
epoxy                     1.5.10               h166bdaf_1    conda-forge
exceptiongroup            1.2.0           py311h06a4308_0  
executing                 2.0.1                    pypi_0    pypi
expat                     2.6.2                h59595ed_0    conda-forge
fastjsonschema            2.19.1                   pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.0          py311h331c9d8_0    conda-forge
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
fusion-blossom            0.2.10                   pypi_0    pypi
gcc                       13.2.0              hc7bed06_10    conda-forge
gcc_bootstrap_linux-64    13.2.0               h6ac0598_7    conda-forge
gcc_impl_linux-64         13.2.0              h9eb54c0_10    conda-forge
gdk-pixbuf                2.42.12              hb9ae30d_0    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
glib                      2.80.2               hf974151_0    conda-forge
glib-tools                2.80.2               hb6ce0ca_0    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
graph-tool                2.69            py311hcde7212_100    conda-forge
graph-tool-base           2.69            py311h6b2c50a_100    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
grikod                    1.0.5                    pypi_0    pypi
gst-plugins-base          1.24.4               h9ad1361_0    conda-forge
gstreamer                 1.24.4               haf2f30d_0    conda-forge
gtk3                      3.24.42              h6d40eaa_0    conda-forge
h11                       0.14.0                   pypi_0    pypi
harfbuzz                  8.5.0                hfac3d4d_0    conda-forge
hicolor-icon-theme        0.17                 ha770c72_2    conda-forge
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7                      pypi_0    pypi
igraph                    0.11.5                   pypi_0    pypi
imageio                   2.34.1                   pypi_0    pypi
importlib-metadata        7.0.1           py311h06a4308_0  
importlib_metadata        7.0.1                hd3eb1b0_0  
ipykernel                 6.29.4                   pypi_0    pypi
ipython                   8.25.0          py311h06a4308_0  
isoduration               20.11.0                  pypi_0    pypi
jax                       0.4.27             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.23          py311h6a678d5_0  
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
json5                     0.9.25                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.22.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            8.6.2                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.1                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.2.2                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.2                   pypi_0    pypi
kernel-headers_linux-64   3.10.0              h57e8cba_10  
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py311h9547e67_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libboost                  1.84.0               hba137d9_3    conda-forge
libboost-python           1.84.0          py311h5510f57_3    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang-cpp15            15.0.7          default_h127d8a8_5    conda-forge
libclang13                18.1.7          default_h087397f_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-devel_linux-64     13.2.0             hdb50d1a_110    conda-forge
libgcc-ng                 13.2.0              h77fa898_10    conda-forge
libgcrypt                 1.10.3               hd590300_0    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0              h69a702a_10    conda-forge
libgfortran5              13.2.0              h3d2ce59_10    conda-forge
libgirepository           1.80.1               h003a4f0_0    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   13.2.0              h77fa898_10    conda-forge
libgpg-error              1.49                 h4f305b6_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm14                 14.0.6               hdb19cb5_3  
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libllvm18                 18.1.7               hb77312f_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21               h043d6bf_0  
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.3                 ha72fbe1_0    conda-forge
librsvg                   2.58.1               hadf69e7_0    conda-forge
libsanitizer              13.2.0              h6ddb7a1_10    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libsystemd0               255                  h3516f8a_1    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h662e7e4_0    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvmlite                  0.43.0          py311he1b5a44_0    numba
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.0                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mitiq                     0.37.0                   pypi_0    pypi
ml-dtypes                 0.4.0                    pypi_0    pypi
mpg123                    1.32.6               h59595ed_0    conda-forge
mpmath                    1.3.0                    pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy                      1.10.0                   pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
mysql-common              8.3.0                hf1915f5_4    conda-forge
mysql-libs                8.3.0                hca2cd23_4    conda-forge
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.5                  h59595ed_0    conda-forge
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.100                hca3bf56_0    conda-forge
numba                     0.60.0          np2.0py3.11hb11b5cc_g53e976f1b_0    numba
numpy                     2.0.0                    pypi_0    pypi
opencv-python             4.10.0.82                pypi_0    pypi
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
opt-einsum                3.3.0                hd8ed1ab_2    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1  
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.2.2           py311h14de704_1    conda-forge
pandocfilters             1.5.1                    pypi_0    pypi
pango                     1.54.0               h84a9a3c_0    conda-forge
parso                     0.8.4                    pypi_0    pypi
pbr                       6.0.0                    pypi_0    pypi
pcre2                     10.43                hcad00b1_0    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.3.0          py311h18e6fac_0    conda-forge
pip                       24.0            py311h06a4308_0  
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              4.2.2                    pypi_0    pypi
ply                       3.11               pyhd8ed1ab_2    conda-forge
pptree                    3.1                      pypi_0    pypi
pptrees                   1.3.6                    pypi_0    pypi
print-tree                1.0.0                    pypi_0    pypi
print-tree2               0.9.10                   pypi_0    pypi
prometheus-client         0.20.0                   pypi_0    pypi
prompt-toolkit            3.0.46                   pypi_0    pypi
prompt_toolkit            3.0.43               hd3eb1b0_0  
psutil                    5.9.8                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pulseaudio-client         17.0                 hb77b528_0    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0  
pybind11                  2.12.0          py311hdb19cb5_0  
pybind11-global           2.12.0          py311hdb19cb5_0  
pycairo                   1.26.0          py311h8feb60e_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.7.4                    pypi_0    pypi
pydantic-core             2.18.4                   pypi_0    pypi
pydot                     2.0.0                    pypi_0    pypi
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pygobject                 3.48.2          py311h86ed371_0    conda-forge
pylatexenc                2.10                     pypi_0    pypi
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqrack                   1.28.0                   pypi_0    pypi
pyqt                      5.15.9          py311hf0fb5b6_5    conda-forge
pyqt5-sip                 12.12.2         py311hb755f60_5    conda-forge
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-dotenv             1.0.1                    pypi_0    pypi
python-graphviz           0.20.3                   pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     26.0.3                   pypi_0    pypi
qecp                      0.2.3                    pypi_0    pypi
qecsim                    1.0b9                    pypi_0    pypi
qiskit                    1.1.0                    pypi_0    pypi
qiskit-aer                0.14.2                   pypi_0    pypi
qiskit-aqt-provider       1.5.0                    pypi_0    pypi
qiskit-qrack-provider     0.11.0                   pypi_0    pypi
qsurface                  0.1.5                    pypi_0    pypi
qt-main                   5.15.8              hc9dc06e_21    conda-forge
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
retworkx                  0.14.2                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.18.1                   pypi_0    pypi
ruff                      0.4.9                    pypi_0    pypi
rustworkx                 0.14.2                   pypi_0    pypi
scikit-image              0.23.2                   pypi_0    pypi
scikit-learn              1.5.0                    pypi_0    pypi
scipy                     1.14.0rc2                pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
sigcpp-3.0                3.6.0                h59595ed_0    conda-forge
sip                       6.7.12          py311hb755f60_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sparsehash                2.0.4                hcb278e6_1    conda-forge
stack-data                0.6.3                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0  
stevedore                 5.2.0                    pypi_0    pypi
symengine                 0.11.0                   pypi_0    pypi
sympy                     1.12.1                   pypi_0    pypi
sysroot_linux-64          2.17                h57e8cba_10  
tabulate                  0.9.0                    pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
texttable                 1.7.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.5.22                pypi_0    pypi
tinycss2                  1.3.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py311h331c9d8_0    conda-forge
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3          py311h06a4308_0  
types-python-dateutil     2.9.0.20240316           pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h04d1e81_0  
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
wayland                   1.23.0               h5291e77_0    conda-forge
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.6.0                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
wheel                     0.43.0          py311h06a4308_0  
xarray                    2024.6.0           pyhd8ed1ab_1    conda-forge
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xeus                      3.2.0                h06414e2_0    conda-forge
xeus-python               0.15.12                  pypi_0    pypi
xeus-python-shell         0.6.1                    pypi_0    pypi
xeus-python-shell-raw     0.5.0              pyhd8ed1ab_0    conda-forge
xeus-zmq                  1.3.0                h6b5a882_0    conda-forge
xkeyboard-config          2.42                 h4ab18f5_0    conda-forge
xorg-compositeproto       0.4.2             h7f98852_1001    conda-forge
xorg-damageproto          1.2.1             h7f98852_1002    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxcomposite        0.4.6                h0b41bf4_1    conda-forge
xorg-libxcursor           1.2.0                h0b41bf4_1    conda-forge
xorg-libxdamage           1.1.5                h7f98852_1    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxinerama          1.1.5                h27087fc_0    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-util-macros          1.19.3               h7f98852_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.6                h5eee18b_1  
zeromq                    4.3.5                h6a678d5_0  
zipp                      3.17.0          py311h06a4308_0  
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.19.0          py311hd4cff14_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
conda info

     active environment : x11
    active env location : /home/*/miniconda3/envs/x11
            shell level : 1
       user config file : /home/*/.condarc
 populated config files : /home/*/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.3.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=k10
                          __conda=24.5.0=0
                          __glibc=2.39=0
                          __linux=6.9.3=0
                          __unix=0=0
       base environment : /home/*/miniconda3  (writable)
      conda av data dir : /home/*/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/*/miniconda3/pkgs
                          /home/*/.conda/pkgs
       envs directories : /home/*/miniconda3/envs
                          /home/*/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.3 Linux/6.9.3-060903-generic ubuntu/24.04 glibc/2.39 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by ehfd** [comment]
I have a feeling that this should have been solved now, but needs confirmation.
